### ISSUE TITLE
运行preprocess.sh的时候出现了这个问题

### ISSUE THREAD

**Issue by daisir8** [yy-degit/Scented-EAE#1]
(textee) ubuntu@lenovo:~/下载/Scented-EAE-main$ ./preprocess.sh
Traceback (most recent call last):
  File "preprocess/data_preprocessing.py", line 292, in <module>
    os.mkdir(args.output_path)
FileNotFoundError: [Errno 2] No such file or directory: 'data/new_data/ace'
cp: 无法创建普通文件'data/new_data/ace/template.json': 没有那个文件或目录

**Comment by yy-degit** [comment]
你看下你这个有没有说不存在的那个文件夹的父目录，data/new_data，另外抱歉，我这个运行写的太简单了，今天我会更新一下readme



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 上午10:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yy-degit/Scented-EAE] 运行preprocess.sh的时候出现了这个问题 (Issue #1)




 
(textee) ***@***.***:~/下载/Scented-EAE-main$ ./preprocess.sh
 Traceback (most recent call last):
 File "preprocess/data_preprocessing.py", line 292, in 
 os.mkdir(args.output_path)
 FileNotFoundError: [Errno 2] No such file or directory: 'data/new_data/ace'
 cp: 无法创建普通文件'data/new_data/ace/template.json': 没有那个文件或目录

**Comment by daisir8** [comment]
ok。我把这个文件夹的父目录给建好了之后，之前的问题不存在了，但是又出现了“FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_data/ace/train.json”的问题，但是这次就算建好父目录还是没有解决问题，等你更新叭，麻烦作者了，谢谢

**Comment by yy-degit** [comment]
已经更新完毕！有问题欢迎继续讨论（代码也有所更新，之前的不太全）

**Comment by 2551120365** [comment]
> ok。我把这个文件夹的父目录给建好了之后，之前的问题不存在了，但是又出现了“FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_data/ace/train.json”的问题，但是这次就算建好父目录还是没有解决问题，等你更新叭，麻烦作者了，谢谢

请问这个解决了吗？我也报这个错误了

**Comment by 2551120365** [comment]
> 已经更新完毕！有问题欢迎继续讨论（代码也有所更新，之前的不太全）

您好，现在的代码好像还是有这个错误 “FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_data/ace/train.json

**Comment by 2551120365** [comment]
您好请问这个是需要输入什么特定值吗？这个运行过后，后面发现没有生成train.json文件
def debug_if(cond):
    if cond:
        import ipdb; ipdb.set_trace()

**Comment by yeliya1** [comment]
> > ok。我把这个文件夹的父目录给建好了之后，之前的问题不存在了，但是又出现了“FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_data/ace/train.json”的问题，但是这次就算建好父目录还是没有解决问题，等你更新叭，麻烦作者了，谢谢
> 
> 请问这个解决了吗？我也报这个错误了

解决了吗请问，我也是一样的报错

**Comment by yy-degit** [comment]
> > ok。我把这个文件夹的父目录给建好了之后，之前的问题不存在了，但是又出现了“FileNotFoundError: [Errno 2] No such file or directory: 'data/raw_data/ace/train.json”的问题，但是这次就算建好父目录还是没有解决问题，等你更新叭，麻烦作者了，谢谢
> 
> 请问这个解决了吗？我也报这个错误了

请严格按照readme执行数据预处理，这个问题显然是数据处理步骤不对了，从你的ace最原始数据-->处理出第一个train.json就不对，优先怀疑的：
1. 原始数据位置放对了吗？
2. 我写的很详细的ace/requirements.txt里可能有些需要手动安装的东西，都安装好了吗
3. 各种库的版本合理否？
你再看看，不行你按照我给的我参考的那篇论文（也很经典）的代码处理也可以
（推测你库没安好）

**Comment by yy-degit** [comment]
> 您好请问这个是需要输入什么特定值吗？这个运行过后，后面发现没有生成train.json文件 def debug_if(cond): if cond: import ipdb; ipdb.set_trace()

不需要，这个代码是报错了就打印追踪问题所在，和我们主线无关哈
