### ISSUE TITLE
请问模型换成T5需要做哪些调整？

### ISSUE THREAD

**Issue by bearshr** [yy-degit/Scented-EAE#2]
我希望使用T5来复现，但是将模型替换后出现了缺失 decoder_input_ids 的问题，如下所示：
```
Traceback (most recent call last):
  File "/mnt/bn/songhengrui-nas/Scented-EAE/main.py", line 85, in <module>
    main()
  File "/mnt/bn/songhengrui-nas/Scented-EAE/main.py", line 68, in main
    framework.train(train_loader, valid_loader)
  File "/mnt/bn/songhengrui-nas/Scented-EAE/trainer/framework.py", line 66, in train
    _, _, loss = self.model(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/bn/songhengrui-nas/Scented-EAE/models/model.py", line 188, in forward
    model_outputs = self.model(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/t5/modeling_t5.py", line 1426, in forward
    decoder_outputs = self.decoder(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/t5/modeling_t5.py", line 932, in forward
    raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
```

因此我使用了 BartModel 定义的 decoder_input_ids 初始化函数：
```
def shift_tokens_right(self, input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int):
    """
    Shift input ids one token to the right.
    """
    shifted_input_ids = input_ids.new_zeros(input_ids.shape)
    shifted_input_ids[:, 1:] = input_ids[:, :-1].clone()
    shifted_input_ids[:, 0] = decoder_start_token_id

    if pad_token_id is None:
        raise ValueError("self.model.config.pad_token_id has to be defined.")
    # replace possible -100 values in labels by `pad_token_id`
    shifted_input_ids.masked_fill_(shifted_input_ids == -100, pad_token_id)
    return shifted_input_ids`
```

并对 ScentedEAE.forward() 中的模型输入做了如下修改：
```
model_outputs = self.model(
    input_ids=encoder_input_ids,
    attention_mask=encoder_attention_mask,
    decoder_input_ids=self.shift_tokens_right(encoder_input_ids, self.config.pad_token_id, self.config.decoder_start_token_id),
    return_dict=True
)
```
但是这样处理之后，**T5 的 Arg-C F1 只有17%**。请问该如何修改以正确复现呢？

**Comment by yy-degit** [comment]
调整主要有以下几个部分：
1. main.py函数中：
```
MODEL_CALSSES = {'bart': (BartConfig, YyModel, BartTokenizerFast), 't5': (AutoConfig, YyModel, AutoTokenizer)}
yymodel = YyModel(config, load_model_path)
```
2. model.py函数中：
```
class YyModel(T5PreTrainedModel):
          def __init__(self, config, load_model_path):
              super().__init__(config)
              self.config = config
              self.t5 = T5Model.from_pretrained(load_model_path)


model_outputs = self.t5(
    input_ids=encoder_input_ids,
    attention_mask=encoder_attention_mask,
    decoder_input_ids=encoder_input_ids,
    decoder_attention_mask=encoder_attention_mask,
    return_dict=True
)
hidden_states = model_outputs.last_hidden_state
```

**Comment by bearshr** [comment]
感谢！这个问题看起来解决了。但您似乎没有提供 schema.json 文件，我使用 entity_map.json 文件并自行补充了一些缺失的内容，但复现效果不理想。请问可以上传一下原始的 schema.json 文件吗？

**Comment by yy-degit** [comment]
唉？你运行preprocess.sh里面能自动生成啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月27日(周三) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yy-degit/Scented-EAE] 请问模型换成T5需要做哪些调整？ (Issue #2)




 
感谢！这个问题看起来解决了。但您似乎没有提供 schema.json 文件，我使用 entity_map.json 文件并自行补充了一些缺失的内容，但复现效果不理想。请问可以上传一下原始的 schema.json 文件吗？

**Comment by bearshr** [comment]
非常感谢！因为我有预处理过的数据集，所以之前没有关注这个文件。
不过我使用T5-large（770M）训练时，loss 一直在30左右浮动，而用 BART 时就能正常降低。请问你们在训练时遇到过类似的情况吗？我尝试过 lr=1e-4/1e-5，其他超参数没有调整。

**Comment by yy-degit** [comment]
哦，你这显然梯度消失了(因为如果网络正常只是方法差劲的话损失还是能下降的)，


我想下，我跑3b的时候学习率是1e-4，输入长度270，其他参数没咋变。


我认为你还能调整的：
1. 确定t5预训练模型的参数加进来了，此处看调试信息，千万别随机初始化了
2. 调整学习率
3. 模型的forward函数里有个scale，这个东西默认写的根号d，可以尝试换成更大的数字或更小的数字
4. 其他数据编码侧的问题，数据处理出错问题等


有问题欢迎再问



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月27日(周三) 下午3:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yy-degit/Scented-EAE] 请问模型换成T5需要做哪些调整？ (Issue #2)




 
非常感谢！因为我有预处理过的数据集，所以之前没有关注这个文件。
 不过我使用T5-large（770M）训练时，loss 一直在30左右浮动，而用 BART 时就能正常降低。请问你们在训练时遇到过类似的情况吗？我尝试过 lr=1e-4/1e-5，其他超参数没有调整。

**Comment by bearshr** [comment]
抱歉没说清楚，我尝试了两种情况：
1.  使用 `self.t5 = T5Model.from_pretrained(load_model_path)`
这时 train_loss 不会降低
模型 load 的输出为：
```
loading weights file models/t5-large/pytorch_model.bin
All model checkpoint weights were used when initializing T5Model.

All the weights of T5Model were initialized from the model checkpoint at models/t5-large.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5Model for predictions without further training.
Some weights of the model checkpoint at models/t5-large were not used when initializing ScentedEAE_T5: ['encoder.block.1.layer.0.SelfAttention.q.weight'...]
- This IS expected if you are initializing ScentedEAE_T5 from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ScentedEAE_T5 from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ScentedEAE_T5 were not initialized from the model checkpoint at models/t5-large and are newly initialized: ['model.encoder.block.9.layer.0.SelfAttention.k.weight'...]
```
2. 使用 `self.t5 = T5Model(config)`
这时 train_loss 可以正常降低，但 eval_loss 在 30 左右就不下降了（1～2 epoch）。最终 F1 只有 30% 左右。lr=1e-4。
模型 load 的输出为：
```
loading weights file models/t5-large/pytorch_model.bin

Some weights of the model checkpoint at models/t5-large were not used when initializing ScentedEAE_T5: ['encoder.block.1.layer.0.SelfAttention.q.weight'...]
- This IS expected if you are initializing ScentedEAE_T5 from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ScentedEAE_T5 from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ScentedEAE_T5 were not initialized from the model checkpoint at models/t5-large and are newly initialized: ['model.encoder.block.9.layer.0.SelfAttention.k.weight'...]

```

另外，没有质疑方法的意思。感谢大佬耐心解惑！

**Comment by yy-degit** [comment]
你可能得先找一下t5参数没加载进来的问题了，我这段是这样的：
```
loading weights file EAE/plm/t5-3b/pytorch_model.bin
Some weights of the model checkpoint at EAE/plm/t5-3b were not used when initializing T5Model: ['lm_head.weight']
- This IS expected if you are initializing T5Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of T5Model were initialized from the model checkpoint at EAE/plm/t5-3b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5Model for predictions without further training.
```

你再仔细看下我的代码，会不会是哪里忘改了
1. from transformers.models.t5.modeling_t5 import T5Model, T5PreTrainedModel
2. 主模型的继承类换T5PreTrainedModel了
3. main加载参数的部分大概是
```
args.plm_type="t5"
config_class, model_class, tokenizer_class = MODEL_CALSSES[args.plm_type]
load_model_path = args.model_name_or_path if args.do_train else args.load_model_path
config = config_class.from_pretrained(load_model_path)
config = add_config_params(args, config)
yymodel = YyModel(config, load_model_path)
tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path, add_special_tokens=True)
```
4. 另外这个好了的话记得他max_length也不是bart分词的那个长度了，前面提过

**Comment by bearshr** [comment]
现在正常了，非常感谢！祝大佬paper多多～

**Comment by 2551120365** [comment]
> 我希望使用T5来复现，但是将模型替换后出现了缺失 decoder_input_ids 的问题，如下所示：
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/bn/songhengrui-nas/Scented-EAE/main.py", line 85, in <module>
>     main()
>   File "/mnt/bn/songhengrui-nas/Scented-EAE/main.py", line 68, in main
>     framework.train(train_loader, valid_loader)
>   File "/mnt/bn/songhengrui-nas/Scented-EAE/trainer/framework.py", line 66, in train
>     _, _, loss = self.model(
>   File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/mnt/bn/songhengrui-nas/Scented-EAE/models/model.py", line 188, in forward
>     model_outputs = self.model(
>   File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/transformers/models/t5/modeling_t5.py", line 1426, in forward
>     decoder_outputs = self.decoder(
>   File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/transformers/models/t5/modeling_t5.py", line 932, in forward
>     raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
> ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
> ```
> 
> 因此我使用了 BartModel 定义的 decoder_input_ids 初始化函数：
> 
> ```
> def shift_tokens_right(self, input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int):
>     """
>     Shift input ids one token to the right.
>     """
>     shifted_input_ids = input_ids.new_zeros(input_ids.shape)
>     shifted_input_ids[:, 1:] = input_ids[:, :-1].clone()
>     shifted_input_ids[:, 0] = decoder_start_token_id
> 
>     if pad_token_id is None:
>         raise ValueError("self.model.config.pad_token_id has to be defined.")
>     # replace possible -100 values in labels by `pad_token_id`
>     shifted_input_ids.masked_fill_(shifted_input_ids == -100, pad_token_id)
>     return shifted_input_ids`
> ```
> 
> 并对 ScentedEAE.forward() 中的模型输入做了如下修改：
> 
> ```
> model_outputs = self.model(
>     input_ids=encoder_input_ids,
>     attention_mask=encoder_attention_mask,
>     decoder_input_ids=self.shift_tokens_right(encoder_input_ids, self.config.pad_token_id, self.config.decoder_start_token_id),
>     return_dict=True
> )
> ```
> 
> 但是这样处理之后，**T5 的 Arg-C F1 只有17%**。请问该如何修改以正确复现呢？

**Comment by 2551120365** [comment]
> 现在正常了，非常感谢！祝大佬paper多多～

您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题

**Comment by 2551120365** [comment]
> 抱歉没说清楚，我尝试了两种情况：
> 
> 1. 使用 `self.t5 = T5Model.from_pretrained(load_model_path)`
>    这时 train_loss 不会降低
>    模型 load 的输出为：
> 
> ```
> loading weights file models/t5-large/pytorch_model.bin
> All model checkpoint weights were used when initializing T5Model.
> 
> All the weights of T5Model were initialized from the model checkpoint at models/t5-large.
> If your task is similar to the task the model of the checkpoint was trained on, you can already use T5Model for predictions without further training.
> Some weights of the model checkpoint at models/t5-large were not used when initializing ScentedEAE_T5: ['encoder.block.1.layer.0.SelfAttention.q.weight'...]
> - This IS expected if you are initializing ScentedEAE_T5 from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing ScentedEAE_T5 from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Some weights of ScentedEAE_T5 were not initialized from the model checkpoint at models/t5-large and are newly initialized: ['model.encoder.block.9.layer.0.SelfAttention.k.weight'...]
> ```
> 
> 2. 使用 `self.t5 = T5Model(config)`
>    这时 train_loss 可以正常降低，但 eval_loss 在 30 左右就不下降了（1～2 epoch）。最终 F1 只有 30% 左右。lr=1e-4。
>    模型 load 的输出为：
> 
> ```
> loading weights file models/t5-large/pytorch_model.bin
> 
> Some weights of the model checkpoint at models/t5-large were not used when initializing ScentedEAE_T5: ['encoder.block.1.layer.0.SelfAttention.q.weight'...]
> - This IS expected if you are initializing ScentedEAE_T5 from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing ScentedEAE_T5 from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Some weights of ScentedEAE_T5 were not initialized from the model checkpoint at models/t5-large and are newly initialized: ['model.encoder.block.9.layer.0.SelfAttention.k.weight'...]
> ```
> 
> 另外，没有质疑方法的意思。感谢大佬耐心解惑！

在吗，跪求啊

**Comment by bearshr** [comment]
> > 现在正常了，非常感谢！祝大佬paper多多～
> 
> 您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题

我用的是这里的预处理代码：https://github.com/THU-KEG/OmniEvent ，你可以检查一下 requirements 里包的版本是否一致

**Comment by 2551120365** [comment]
> > > 现在正常了，非常感谢！祝大佬paper多多～
> > 
> > 
> > 您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题
> 
> 我用的是这里的预处理代码：https://github.com/THU-KEG/OmniEvent ，你可以检查一下 requirements 里包的版本是否一致

谢谢现在解决了，我现在换成T5模型发现损失也在30左右，跟您上面的问题很相似，您是采取了什么措施吗

**Comment by bearshr** [comment]
> > > > 现在正常了，非常感谢！祝大佬paper多多～
> > > 
> > > 
> > > 您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题
> > 
> > 
> > 我用的是这里的预处理代码：https://github.com/THU-KEG/OmniEvent ，你可以检查一下 requirements 里包的版本是否一致
> 
> 谢谢现在解决了，我现在换成T5模型发现损失也在30左右，跟您上面的问题很相似，您是采取了什么措施吗

1. main.py 中
```
MODEL_CALSSES = {'bart': (BartConfig, ScentedEAE, BartTokenizerFast), 't5': (T5Config, ScentedEAE_T5, AutoTokenizer)}
……
eaemodel = model_class(config, load_model_path)
```
2. model.py 中
```
class ScentedEAE_T5(T5PreTrainedModel):
    def __init__(self, config, load_model_path):
        super().__init__(config)
        self.config = config
        self.model = T5Model.from_pretrained(load_model_path)
```

**Comment by yy-degit** [comment]
> > > 现在正常了，非常感谢！祝大佬paper多多～
> > 
> > 
> > 您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题
> 
> 我用的是这里的预处理代码：https://github.com/THU-KEG/OmniEvent ，你可以检查一下 requirements 里包的版本是否一致

正好问下，我的ace数据预处理代码你也运行不出来结果吗？大概是啥原因呢？我这面库都安好了就没问貌似

**Comment by bearshr** [comment]
> > > > 现在正常了，非常感谢！祝大佬paper多多～
> > > 
> > > 
> > > 您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题
> > 
> > 
> > 我用的是这里的预处理代码：https://github.com/THU-KEG/OmniEvent ，你可以检查一下 requirements 里包的版本是否一致
> 
> 正好问下，我的ace数据预处理代码你也运行不出来结果吗？大概是啥原因呢？我这面库都安好了就没问貌似

奥我没有运行你的预处理代码，因为我有预处理过的数据了，为了避免因为预处理过程不一样导致的结果差异就用了我之前的。你可以问一下 @2551120365 遇到了什么问题。

**Comment by yy-degit** [comment]
噢噢噢，好滴



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月9日(周四) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [yy-degit/Scented-EAE] 请问模型换成T5需要做哪些调整？ (Issue #2)




     
现在正常了，非常感谢！祝大佬paper多多～
  
您好，您能分享一下您的代码吗，我在数据处理阶段，ACE数据集就遇到了报错的问题
  
我用的是这里的预处理代码：https://github.com/THU-KEG/OmniEvent ，你可以检查一下 requirements 里包的版本是否一致
  
正好问下，我的ace数据预处理代码你也运行不出来结果吗？大概是啥原因呢？我这面库都安好了就没问貌似
  
奥我没有运行你的预处理代码，因为我有预处理过的数据了，为了避免因为预处理过程不一样导致的结果差异就用了我之前的。你可以问一下 @2551120365 遇到了什么问题。
