### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by yeliya1** [yy-degit/Scented-EAE#3]
$ bash run.sh
C:\anaconda\envs\yeliyax\lib\site-packages\transformers\models\bart\modeling_bart.py:786: FutureWarning: The class `PretrainedBartModel` has been depreciated, please use `BartPreTrainedModel` instead.
  warnings.warn(
Traceback (most recent call last):
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001BEC7A33A90>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\anaconda\envs\yeliyax\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /plm/bart-base/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001BEC7A33A90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /plm/bart-base/resolve/main/config.json (Ca
used by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001BEC7A33A90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 73b7b67c-adf3-458a-a43e-c94fd7a7ddc6)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\anaconda\envs\yeliyax\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\huggingface_hub\file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\pycode\Scented-EAE-main\Scented-EAE-main\main.py", line 81, in <module>
    main()
  File "C:\pycode\Scented-EAE-main\Scented-EAE-main\main.py", line 46, in main
    config = config_class.from_pretrained(load_model_path)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\transformers\configuration_utils.py", line 550, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\transformers\configuration_utils.py", line 590, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\anaconda\envs\yeliyax\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\anaconda\envs\yeliyax\lib\site-packages\transformers\utils\hub.py", line 446, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like plm/bart-base is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
您好，请问这个报错是什么原因导致的？

**Comment by yy-degit** [comment]
我首先怀疑你没下载好bart预训练模型到指定位置，因为这个代码看着像要原地下一个bart给你，但是连不上huggingface或者啥的失败，但其实你得自己下载好bart
